### ISSUE TITLE
My code gave me two errors first : RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x256 and 400x120) second: I don't see a LeNet class in your code,just a Net class.

### ISSUE THREAD

**Issue by 1BTU** [MaitreChen/openvino-lenet-sample#1]
My code gave me two errors
first :
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x256 and 400x120)
second:
I don't see a LeNet class in your code,just a Net class.
![Snipaste_2023-04-24_20-10-52](https://user-images.githubusercontent.com/90665781/233992258-9245b644-22a7-4426-98aa-eb0ae14cffe2.png)

**Comment by MaitreChen** [comment]
I'm so sorry, and I have updated "net.py" again to fix the problem you mentioned.
